### ISSUE TITLE
Option To Filter Webservice

### ISSUE THREAD

**Issue by Suterusu1337** [Jrogo7/VenueManager#2]
Right now, the webservice will post the entire list of users, including those not currently in the house. This can be large for outdoor events which may see upwards of 500-600+ unique visitors.

Add option to filter and only post the inhouse/can see users and not the entire list. Server side we apply this filter anyway so it would make it more convenient than sending massive jsons to parse.

**Comment by Jrogo7** [comment]
Can do. Ill try and get this in soon.

**Comment by Jrogo7** [comment]
@Suterusu1337 Can you give it a try when you have time and see if it is working for you?
